defaults:
  - colorspace: lab
  - _self_

seed: 1
use_tb: true
save_snapshot: false

stl10_dataset_path: ./img/stl10

image_size: 224
crop: 0.5
batch_size: 256 # Number of samples (number of negatives + 1)

num_epochs: 80
lr: 0.001
beta_1: 0.5
beta_2: 0.999
momentum: 0.9
weight_decay: 1e-4

temperature: 0.05 # Temperature in the critic function
full_graph: true # Core view or full graph paradigm

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
