defaults:
  - colorspace: lab
  - model@_global_: alexnet
  - _self_

seed: 1
use_tb: true
save_snapshot: true

stl10_dataset_path: ./img/stl10

crop: 0.5

lr: 0.001
beta_1: 0.5
beta_2: 0.999
momentum: 0.9
weight_decay: 1e-4

temperature: 0.05 # Temperature in the critic function
full_graph: true # Core view or full graph paradigm

num_class_epochs: 15

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
    # dir: ./exp_local/2021.12.02/012242_
