defaults:
  - colorspace: lab
  - model@_global_: alexnet
  - _self_

seed: 1
use_tb: true
save_snapshot: true

stl10_dataset_path: ./img/stl10

lr: 0.001
beta_1: 0.5
beta_2: 0.999
momentum: 0.5
low_crop: 0.08

temperature: 0.05 # Temperature in the critic function
full_graph: true # Core view or full graph paradigm

num_class_epochs: 150

exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}
hydra:
  run:
    dir: ./exp_local/${exp_group}/${exp_id}
    # dir: ./exp_local/2021.12.02/012242_
