encoder:
  _target_: nets.HalfAlexNet
  feat_dim: 128
  pool_type: 'max'

image_size: 224
batch_size: 256

num_enc_epochs: 50

layer: 5

im_norm_mean: [(0 + 100) / 2, (-86.183 + 98.233) / 2, (-107.857 + 94.478) / 2]
im_norm_std: [(100 - 0) / 2, (86.183 + 98.233) / 2, (107.857 + 94.478) / 2]

